# -*- coding: utf-8 -*-
"""223136_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykbY_5s4oHWo_lrMQnsOk3B5k7foGoVh

Лабораториска вежба 3 – Генерирање
природен јазик

Задача 1

Со користење на моделите T5 и FLAN-T5 креирајте EncoderDecoder модел базиран
на архитектурата Transformer кој ќе прави трансформација на реченица која
содржи негативен сентимент во реченица која содржи позитивен сентимент. За
трансформација на податочното множество во формат соодветен за тренирање
користете ја функцијата create_transformers_train_data од скриптата
seq2seq.py.
Истренираниот модел евалуирајте го со метриките: BLEU и BERTScore.
Споредете ги функциите на загуба и евалуационите метрики за различни
хиперпараметри на моделот (рата на учење, број на епохи, ...). Како се менуваат
перформансите на моделот?
"""

!pip install -q evaluate sacrebleu bert-score

import pandas as pd
from torch.optim import AdamW
from evaluate import load
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq
from seq2seq import create_transformers_train_data, train_transformer, decode_with_transformer

data = pd.read_csv("test_en_parallel.txt", sep="\t", header=None)
data.columns = ["Negative", "Positive"]
data.head()

neg, pos = [], []

with open("test_en_parallel.txt", encoding="utf-8") as f:
    for line in f:
        parts = line.rstrip("\n").split("\t")
        if len(parts) != 2:
            continue
        n, p = parts
        neg.append(n.strip())
        pos.append(p.strip())

print("pairs:", len(neg))
print("NEG example:", neg[0])
print("POS example:", pos[0])

instruction = "Rewrite to positive sentiment: "
neg_with_ins = [instruction + s for s in neg]

print(neg[0])
print(neg_with_ins[0])

from sklearn.model_selection import train_test_split

X_train, X_tmp, y_train, y_tmp = train_test_split(
    neg_with_ins, pos, test_size=0.2, random_state=42
)
X_dev, X_test, y_dev, y_test = train_test_split(
    X_tmp, y_tmp, test_size=0.5, random_state=42
)

print("train/dev/test:", len(X_train), len(X_dev), len(X_test))

model_name = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

train_set = create_transformers_train_data(X_train, y_train, tokenizer)
dev_set   = create_transformers_train_data(X_dev,   y_dev,   tokenizer)

train_set

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)
train_loader = DataLoader(train_set, batch_size=16, shuffle=True, collate_fn=data_collator)

optimizer = AdamW(model.parameters(), lr=5e-4)
train_transformer(model, train_loader, optimizer, 3)

num_test_samples = 50

test_inputs = X_test[:num_test_samples]
test_references = y_test[:num_test_samples]

test_predictions = []

for inp in test_inputs:
    generated_text = decode_with_transformer(inp, tokenizer, model)
    test_predictions.append(generated_text)

for i in range(num_test_samples):
    print(f"Example {i+1}")
    print("NEG:", test_inputs[i].replace("Rewrite to positive sentiment: ", ""))
    print("GEN:", test_predictions[i])
    print("REF:", test_references[i])
    print("-"*60)

from evaluate import load

bleu_metric = load("bleu")

bleu_results = bleu_metric.compute(
    predictions=test_predictions,
    references=test_references
)

bleu_results

bertscore_metric = load("bertscore")

bertscore_results = bertscore_metric.compute(
    predictions=test_predictions,
    references=test_references,
    model_type="microsoft/deberta-xlarge-mnli"
)

avg_f1 = sum(bertscore_results["f1"]) / len(bertscore_results["f1"])
avg_f1

"""„BLEU метриката има пониска вредност бидејќи моделот генерира парафразирани позитивни реченици кои не се идентични со референтните. Од друга страна, BERTScore постигнува повисока F1 вредност (~0.75), што укажува дека генерираните реченици се семантички слични и успешно го менуваат сентиментот.“"""

flan_model_name = "google/flan-t5-small"
flan_tokenizer = AutoTokenizer.from_pretrained(flan_model_name)
flan_model = AutoModelForSeq2SeqLM.from_pretrained(flan_model_name)

flan_train_set = create_transformers_train_data(X_train, y_train, flan_tokenizer)

flan_data_collator = DataCollatorForSeq2Seq(tokenizer=flan_tokenizer, model=flan_model)
flan_train_loader = DataLoader(flan_train_set, batch_size=16, shuffle=True, collate_fn=flan_data_collator)

flan_optimizer = AdamW(flan_model.parameters(), lr=5e-4)

flan_epochs = 3
train_transformer(flan_model, flan_train_loader, flan_optimizer, flan_epochs)

test_samples = 50

flan_test_inputs = X_test[:test_samples]
flan_test_references = y_test[:test_samples]

flan_test_predictions = []

for inp in flan_test_inputs:
    generated_text = decode_with_transformer(inp, flan_tokenizer, flan_model)
    flan_test_predictions.append(generated_text)

for i in range(test_samples):
    print(f"Example {i+1}")
    print("NEG:", flan_test_inputs[i].replace("Rewrite to positive sentiment: ", ""))
    print("GEN:", flan_test_predictions[i])
    print("REF:", flan_test_references[i])
    print("-"*60)

FLAN_NUM_TEST = 50
flan_test_inputs = X_test[:FLAN_NUM_TEST]
flan_test_refs = y_test[:FLAN_NUM_TEST]

flan_test_preds = [decode_with_transformer(x, flan_tokenizer, flan_model) for x in flan_test_inputs]

from evaluate import load
bleu_metric = load("bleu")

flan_bleu_results = bleu_metric.compute(predictions=flan_test_preds, references=flan_test_refs)
flan_bleu_results["bleu"]

bertscore_metric = load("bertscore")

flan_bertscore_results = bertscore_metric.compute(
    predictions=flan_test_preds,
    references=flan_test_refs,
    model_type="microsoft/deberta-xlarge-mnli"
)

flan_avg_f1 = sum(flan_bertscore_results["f1"]) / len(flan_bertscore_results["f1"])
flan_avg_f1

print("T5   BLEU:", bleu_results["bleu"], " | BERTScore F1:", avg_f1)
print("FLAN BLEU:", flan_bleu_results["bleu"], " | BERTScore F1:", flan_avg_f1)

"""Добиените резултати се карактеристични за ваков тип задача, при што T5 и FLAN-T5 покажуваат слични перформанси, а малите разлики зависат од поставките и податоците.

Задача 2

Користејќи ja техниката instructional fine-tuning тренирајте го моделот Т5 со
податочното множество за трансформација на реченици кои содржат негативен
сентимент во реченици кои содржат позитивен сентимент.
Истренираниот модел евалуирајте го со метриките: BLEU и BERTScore.
Споредете ги функциите на загуба и евалуационите метрики за различни
хиперпараметри на моделот (рата на учење, број на епохи, ...). Како се менуваат
перформансите на моделот?
Дали овој модел е подобар од моделите во претходнaтa задачa?
"""

instruction = "Rewrite the following sentence to express a positive sentiment: "

X_inst = [instruction + s for s in neg]
y_inst = pos

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X_inst, y_inst, test_size=0.2, random_state=42
)

model_name = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

train_set_2 = create_transformers_train_data(X_train2, y_train2, tokenizer)

collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)
train_loader_2 = DataLoader(
    train_set_2,
    batch_size=16,
    shuffle=True,
    collate_fn=collator
)

optimizer_1 = AdamW(model.parameters(), lr=5e-4)
train_transformer(model, train_loader_2, optimizer_1, epochs=3)

for i in range(5):
    pred = decode_with_transformer(X_test2[i], tokenizer, model)
    print("NEG:", X_test2[i].replace(instruction, ""))
    print("GEN:", pred)
    print("REF:", y_test2[i])
    print("-"*50)

preds2 = [decode_with_transformer(x, tokenizer, model) for x in X_test2[:50]]
refs2  = y_test2[:50]

bleu_2 = load("bleu").compute(predictions=preds2, references=refs2)
bleu_2["bleu"]

bs_2 = load("bertscore").compute(
    predictions=preds2,
    references=refs2,
    model_type="microsoft/deberta-xlarge-mnli"
)
avg_f1_2 = sum(bs_2["f1"]) / len(bs_2["f1"])
avg_f1_2

# different hiperparameters
optimizer_2 = AdamW(model.parameters(), lr=1e-3)
train_transformer(model, train_loader_2, optimizer_2, epochs=3)

N = 50

test_preds = [
    decode_with_transformer(x, tokenizer, model)
    for x in X_test[:N]
]

test_refs = list(y_test[:N])

from evaluate import load

bleu_metric = load("bleu")
bleu_metric.compute(predictions=preds2, references=refs2, smooth=True)["bleu"]

bertscore_metric = load("bertscore")

bertscore_results = bertscore_metric.compute(
    predictions=test_preds,
    references=test_refs,
    model_type="microsoft/deberta-xlarge-mnli"
)

avg_f1 = sum(bertscore_results["f1"]) / len(bertscore_results["f1"])
avg_f1

for i in range(5):
    print(f"Example {i+1}")
    print("NEG:", X_test[:N][i].replace("Rewrite to positive sentiment: ", ""))
    print("GEN:", test_preds[i])
    print("REF:", test_refs[i])
    print("-" * 50)

"""Овие резултати укажуваат дека instructional fine-tuned моделот успешно го менува сентиментот, но генерира повеќе парафразирани реченици, што резултира со пониски автоматски метрики во споредба со моделите од Задача 1.

Задача 3

instructional fine-tuning тренирајте го моделот Т5

Task 1 -
 Tрансформација на реченици кои содржат негативен сентимент во реченици
кои содржат позитивен сентимент.
Истренираниот модел евалуирајте го со метриките: BLEU и BERTScore
"""

data = pd.read_csv("test_en_parallel.txt", sep="\t", header=None)
data.columns = ["Negative", "Positive"]
data.head()

df = pd.read_csv("test_en_parallel.txt", sep="\t", header=None, names=["Negative","Positive"])

#removing style1/2
df = df[~((df["Negative"].str.lower() == "style 1") & (df["Positive"].str.lower() == "style 2"))]

df.head()

"""instruction promt (input/target)

input: rewrite to positive: negative

target: positive
"""

df["input_text"]  = "rewrite to positive: " + df["Negative"].astype(str)
df["target_text"] = df["Positive"].astype(str)
df[["input_text","target_text"]].head()

from datasets import Dataset

dataset = Dataset.from_pandas(df[["input_text","target_text"]])
dataset = dataset.train_test_split(test_size=0.1, seed=42)  # 90% train, 10% val
train_ds = dataset["train"]
val_ds   = dataset["test"]

model_ckpt = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

max_source_len = 128
max_target_len = 128

def preprocess(batch):
    model_inputs = tokenizer(batch["input_text"], max_length=max_source_len, truncation=True)
    labels = tokenizer(batch["target_text"], max_length=max_target_len, truncation=True)
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

train_tok = train_ds.map(preprocess, batched=True, remove_columns=train_ds.column_names)
val_tok   = val_ds.map(preprocess, batched=True, remove_columns=val_ds.column_names)

train_tok[0]

from transformers import (
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)

model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model
)

training_args = Seq2SeqTrainingArguments(

    learning_rate=3e-4,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    predict_with_generate=True,
    fp16=True,
    report_to="none",
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    tokenizer=tokenizer,
    data_collator=data_collator,
)

trainer.train()

import torch

def generate_predictions(dataset, max_new_tokens=64):
    preds = []
    refs = []

    for example in dataset:
        inputs = tokenizer(
            example["input_text"],
            return_tensors="pt",
            truncation=True
        ).to(model.device)

        with torch.no_grad():
            output_ids = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens
            )

        pred = tokenizer.decode(output_ids[0], skip_special_tokens=True)
        preds.append(pred)
        refs.append(example["target_text"])

    return preds, refs


predictions, references = generate_predictions(val_ds)

from evaluate import load

bleu =load("bleu")
bleu_result = bleu.compute(
    predictions=predictions,
    references=[[r] for r in references]
)

print("BLEU:", bleu_result)

import numpy as np

bertscore = load("bertscore")

bert_result = bertscore.compute(
    predictions=predictions,
    references=references,
    lang="en"
)

print("BERTScore F1 (avg):", np.mean(bert_result["f1"]))

"""Истренираниот T5-small модел со instructional fine-tuning покажува висока ефикасност во трансформација на негативни реченици во позитивни, при што значењето на текстот во голема мера е зачувано.

Task 2 -  Препознавање дали одредена реченица содржи позитивен или негативен
сентимент. За оваа задача користете го множеството Yelp_parallel
трансформирано во потребниот формат за класификација на текст.

Истренираниот модел евалуирајте го со метриката точност.
"""

import pandas as pd

df = pd.read_csv("test_en_parallel.txt", sep="\t", header=None, names=["Negative", "Positive"])
df = df[~((df["Negative"].str.lower() == "style 1") & (df["Positive"].str.lower() == "style 2"))]
df.head()

neg_df = pd.DataFrame({
    "input_text": "classify sentiment: " + df["Negative"].astype(str),
    "target_text": "negative"
})

pos_df = pd.DataFrame({
    "input_text": "classify sentiment: " + df["Positive"].astype(str),
    "target_text": "positive"
})

cls_df = pd.concat([neg_df, pos_df], ignore_index=True)
cls_df = cls_df.sample(frac=1, random_state=42).reset_index(drop=True)  # shuffle

cls_df.head(10)

cls_df["target_text"].value_counts()

from datasets import Dataset

cls_dataset = Dataset.from_pandas(cls_df)
cls_dataset = cls_dataset.train_test_split(test_size=0.1, seed=42)

train_cls = cls_dataset["train"]
val_cls   = cls_dataset["test"]

len(train_cls), len(val_cls)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("t5-small")

max_source_len = 128
max_target_len = 8

def preprocess_cls(batch):
    model_inputs = tokenizer(batch["input_text"], max_length=max_source_len, truncation=True)
    labels = tokenizer(batch["target_text"], max_length=max_target_len, truncation=True)
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

train_cls_tok = train_cls.map(preprocess_cls, batched=True, remove_columns=train_cls.column_names)
val_cls_tok   = val_cls.map(preprocess_cls, batched=True, remove_columns=val_cls.column_names)

train_cls_tok[0]

import torch
from transformers import (
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)

model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

training_args = Seq2SeqTrainingArguments(
    output_dir="t5_task2_sentiment_cls",
    learning_rate=3e-4,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    predict_with_generate=True,
    fp16=True,
    report_to="none",
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_cls_tok,
    eval_dataset=val_cls_tok,
    tokenizer=tokenizer,
    data_collator=data_collator,
)

trainer.train()

"""„Истренираниот T5-small модел успешно ја извршува задачата за препознавање на позитивен и негативен сентимент, со стабилна загуба при тренирање и добра способност за класификација.“"""

import torch

def generate_cls_predictions(dataset, tokenizer, model, max_new_tokens=8):
    preds, refs = [], []
    for ex in dataset:
        inputs = tokenizer(ex["input_text"], return_tensors="pt", truncation=True).to(model.device)
        with torch.no_grad():
            out_ids = model.generate(**inputs, max_new_tokens=max_new_tokens)
        pred = tokenizer.decode(out_ids[0], skip_special_tokens=True).strip().lower()
        preds.append(pred)
        refs.append(ex["target_text"].strip().lower())
    return preds, refs

preds, refs = generate_cls_predictions(val_cls, tokenizer, model)

correct = sum(p == r for p, r in zip(preds, refs))
accuracy = correct / len(refs)
print("Accuracy:", accuracy)

"""„Истренираниот T5-small модел постигнува висока точност (91%) при препознавање на позитивен и негативен сентимент, што укажува на ефективна класификација на текстот.“

"""

#different hiperparameters
import torch
from transformers import (
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)

# ====== RUN 2: different learning rate ======
model2 = AutoModelForSeq2SeqLM.from_pretrained("t5-small")
data_collator2 = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model2)

training_args2 = Seq2SeqTrainingArguments(
    output_dir="t5_task2_sentiment_cls_lr1e4",
    learning_rate=1e-4,          # <--
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    predict_with_generate=True,
    fp16=True,
    report_to="none",
)

trainer2 = Seq2SeqTrainer(
    model=model2,
    args=training_args2,
    train_dataset=train_cls_tok,
    eval_dataset=val_cls_tok,
    tokenizer=tokenizer,
    data_collator=data_collator2,
)

train_out2 = trainer2.train()
print("Run 2 training_loss:", train_out2.training_loss)

# ====== ACCURACY (Run 2) ======
def generate_cls_predictions(dataset, tokenizer, model, max_new_tokens=8):
    preds, refs = [], []
    for ex in dataset:
        inputs = tokenizer(ex["input_text"], return_tensors="pt", truncation=True).to(model.device)
        with torch.no_grad():
            out_ids = model.generate(**inputs, max_new_tokens=max_new_tokens)
        pred = tokenizer.decode(out_ids[0], skip_special_tokens=True).strip().lower()
        preds.append(pred)
        refs.append(ex["target_text"].strip().lower())
    return preds, refs

preds2, refs2 = generate_cls_predictions(val_cls, tokenizer, model2)

correct2 = sum(p == r for p, r in zip(preds2, refs2))
accuracy2 = correct2 / len(refs2)
print("Run 2 Accuracy:", accuracy2)

"""„При споредба на различни хиперпараметри кај Task 2, беше забележано дека пониската рата на учење (1e-4) доведува до постабилно учење, но и до нешто пониска точност (88%) во однос на повисоката рата на учење (3e-4), која постигна повисока точност од 91%. Ова укажува дека изборот на ратата на учење значително влијае врз перформансите на моделот.“"""

